### ISSUE TITLE
Processing large CSV file gets stuck

### ISSUE THREAD

**Issue by norwynn** [roadrunnerlenny/etlbox#59] opened 2020-04-05 16:24 UTC
Hi,

I'm trying to process a CSV file, roughly around 9GB with 31M++ rows and 33 columns.  Following the examples, I am able to copy data to an SQL Server database.  But after about 6-7 million rows, the console application starts hogging a lot of memory(95-98%) and stops copying rows to the destination (no row count change during monitoring, had to terminate).

Am I missing something?  Can you give an example on how to resolve?

BTW, as a test, I split the file (1M rows each), iterated through each one and did not encounter the issue.

Thanks!

**Comment by roadrunnerlenny** [comment] 2020-04-05 18:16
Hi, 

Thanks a lot for using ETLBox and reporting your issue. That sounds like a memory leak in ETLbox that shouldn’t happen. 
I would like to try to reproduce this error in my test environment. 

Could you provide my some additional information:
1) the piece of code where you create and execute your dataflow? 
2) which version of ETLBox are you using?

**Comment by norwynn** [comment] 2020-04-06 03:47
HI,

Version: 1.8.3. on .net core console application.

Also got this error now:

![image](https://user-images.githubusercontent.com/20890162/78521392-4c130400-77fc-11ea-950b-9e919ed9030d.png)

Here's some code snipper used:

`


             var result = false;
            CsvSource<T> source = new CsvSource<T>(_srcConnString);
            source.Configuration.Delimiter = "|";
            source.Configuration.TrimOptions = CsvHelper.Configuration.TrimOptions.Trim;

            RowTransformation<ExpandoObject, MyDataObject> rowTrans = new RowTransformation<ExpandoObject, MyDataObject>(
                    row =>
                    {
                        dynamic csvRow = row as ExpandoObject;
                        MyDataObject data = new MyDataObject()
                        {
                            Field01 = csvRow.field01 + "Some Data",
                            .
                            .
                            .
                        };
                        return data;
                    };

            SqlConnectionManager destConnMan = new SqlConnectionManager(_destConnString);
            TruncateTableTask.Truncate(destConnMan, table);
            DbDestination<X> dest = new DbDestination<X>(destConnMan, table);
            source.LinkTo(rowTrans);
            rowTrans.LinkTo(dest);
            source.Execute();
            dest.Wait();            `

**Comment by roadrunnerlenny** [comment] 2020-04-06 21:37
Hi @norwynn ,

I tried to simulate the behavior in my local test environment. 

I create a test that looks like this:
https://github.com/roadrunnerlenny/etlbox/blob/f1518f65810f9b989468117c4d79bbc59ff4119b/TestsPerformance/src/CSVSourceIntoDBTests.cs#L137-L175

This test basically creates a Csv file with 10.000.000 rows, where each row consists of about 1000 characters. In total, each row consumes about 1kb and the total size of the file is about 10GB. The creation of the file can take a while (about 10min on my local machine)

After the file is created, I load the file in my local Sql Server docker image. I created a row transformation that looks very similar to the one above. 
I don't get any unusual behavior or exceptions. The total load time is between 8-10min. I tried it with 2 different batch sizes (1000 and 10.000).  The 10 million rows were always successfully copied into the database. 

So in my environment I can't reproduce the error so far. 
In the screenshot I can see the message "Starting database sync" - this is actually an output which is not produced from ETLBox. It must be something from the underlying ADO.NET provider. 

So could you tell me more about your environment? Are you using on-premise Sql Server or Azure, if on-premise is it on your local machine or somewhere else? 
What is the machine-size where your console app runs? How much free memory is there available?

**Comment by norwynn** [comment] 2020-04-07 02:33
Hi,

I tested the console app with CSV saving to a local Sql Server database Developer Ed. on an AMD A10 5800K with 16GB RAM, SSD.  Also tested on Azure Sql database DTU (S100).  "Starting database sync" is just console output/logging.

I'll also do another test and see if I can reproduce it again.

Thanks!

**Comment by roadrunnerlenny** [comment] 2020-04-10 09:24
Hi @norwynn ,

were you able to get things running?

**Comment by norwynn** [comment] 2020-04-12 06:57
HI, working on it. Will update ASAP.  Thanks!

**Comment by roadrunnerlenny** [comment] 2020-04-16 20:54
Hi @norwynn ,

sorry for the delay getting back to you. 
Thanks for the video, I did the same analysis on my machine. 
On first sight, this looks like a memory leak.
So I made some additional test in my environment. Turns out, that when I run my test in Debug mode, everything works fine - memory consumption stays on "normal" level.
But executing the test in run mode, I get the same extreme memory consumption. So I could reproduce the issue. 

Based on this, I was able to do some further investigations. I learned about GC Pressure, which means that my code is creating and disposing objects so frequently that the Garbage Collection won't be able to clean up disposed objects fast enough. Looked like this is the reason why memory usage gets so high.

I already did some tests, and I think I can create a fix for this in the next couple of days and release a new version pretty soon. 

I tried to create a workaround, but with no luck. So I hope you can wait some more days until I can come up with a fix for this.

**Comment by norwynn** [comment] 2020-04-17 09:25
Thanks!  Will wait for the fix.

**Comment by roadrunnerlenny** [comment] 2020-04-19 22:05
Hi @norwynn , 
Took me longer than expected, but I think I was able to create a fix for this.
The root cause (so far) seems to be somehow the CsvHelper library - I am not 100% sure about this yet, but adding some code that calls the GC to clean up and delay execution for 1 ms significantly reduces the amount of allocated memory in my test environment. I probably will do some more tests on this (these memory leaks are hard to debug), but I guess I will add this fix for the next version already - which I'll probably will release this week. 

Will keep you updated.

**Comment by roadrunnerlenny** [comment] 2020-04-21 19:30
Hi @norwynn ,

just released version 1.8.6 (https://www.nuget.org/packages/ETLBox/1.8.6) which contains a fix to keep memory consumption low. 
Actually `CsvSource` now has a property `ReleaseGCPressureRowCount` which by default is set to 100 - every 100 rows read from the csv source the Garbage Collection is triggered manually and execution is paused for 1 ms. This does not really affect overall performance at all, but it gives the Garbage Collection enough time to keep on disposing unneeded objects and therefore memory consumption stays low. To turn this off, you can set the value to 0. 

Could you try out if this fixes your issue?

**Comment by roadrunnerlenny** [comment] 2020-04-22 19:17
One more thing to add here: 
The default batch size for `DbDestination` is 1000. For SqlServer, you will perhaps get a much better write performance when you increase this to 1000, e.g. like this:
```C#
var dest = new DbDestination(..);
dest.BatchSize = 10000;
```

**Comment by norwynn** [comment] 2020-04-24 14:10
Hi, thanks for the update.  I'll run some tests on the builds.

**Comment by norwynn** [comment] 2020-04-25 17:00
Hi,

I did a couple of simple tests using the new build.  I think the original issue was likely caused when ExpandoObject/Dynamic variables were used. Couple of things:

1. We changed the approach and it is faster if you use regular POCO objects.
2. ReleaseGCPressureRowCount.  I encountered the same CLR error on a single test when value is 0.
3. It is slow when using the default value of 100.  
4. My second test, I was able to finish the 31M rows in about 24 minutes with batch of 50k and ReleaseGCPressureRowCount at 10k.
5. As the ReleaseGCPressureRowCount value increases, the performance gets better, but it plateaus at a certain point.  See screenshot below.  BatchRows is at 50k, ReleaseGCPressureRowCount starts at 100, and increments every 50k rows.  (Note: This is just a rudimentary test.  Counted rows at the transformation phase.  Results may vary depending on machine, code, etc.).

![image](https://user-images.githubusercontent.com/20890162/80284744-df33bf80-8752-11ea-9cd5-e0e46f87a0bf.png)

PS:
Tested revised code using the V1.8.3. and did not encounter issue.

**Comment by roadrunnerlenny** [comment] 2020-04-25 20:14
Hi @norwynn ,

thanks for the tests and detailed analysis. 
I have two questions to your remarks:
- Beside the performance decrease, did you check the memory consumption? I assume it was stable when you used  ReleaseGCPressureRowCount = 100 , but if you choose a higher value (like 1000, 5000 or 10k) , did you observe the memory consumption? In my tests I also could observe a slower read/write performance with ReleaseGCPressureRowCount between 100 and 1000, but for everything above 200 the memory "leaked" again and went out of control.
- you wrote in PS that you tested agian with version 1.8.3 - does that mean that this version did not have issues with the memory?

**Comment by norwynn** [comment] 2020-04-26 02:25
hi @roadrunnerlenny ,

Based on my test, these are the memory consumption based on the TaskMan info.

- Memory consumption @  ReleaseGCPressureRowCount = 0 is is between 150-350MB. I noticed that I sometimes get this error: _Fatal error. Internal CLR error. (0x80131506)_. Intermittent. Unstable.
- Memory consumption @  ReleaseGCPressureRowCount >= 100 is between 100-350MB.  Higher ReleaseGCPressureRowCount values, higher performance. More stable.

Regarding V1.8.3, you'll still get the memory issues if you use ExpandoObject/Dynamic vars.  It still went out of control and crashed.  Otherwise, I was able to make 2 successful runs, but I am not 100% certain if i wouldn't encounter _Fatal error. Internal CLR error. (0x80131506)_.

So I guess the key takeaway, avoid using dynamic vars on really, really large files without the ReleaseGCPressureRowCount option.  Overall, happy with the fix.

Screenshot on Debug mode, BatchRows=50k, ReleaseGCPressureRowCount = 10k
![image](https://user-images.githubusercontent.com/20890162/80295752-02d52500-87a8-11ea-8a14-a3d4a46ecbc2.png)

**Comment by roadrunnerlenny** [comment] 2020-04-27 21:28
Hi @norwynn ,

thanks for the analysis and the details of your tests. 
I thought about it a little bit, so I think these are things that needs to be considered:
- the fix with the RelaseGCPressureRowCount property seems to work and is giving you some flexibility to adjust the performance to your needs. 
- Still, for me it's more like a quick&dirty fix, because your detailed anaylsis shows that there are different aspects that need to be taken into account (e.g. ExpandoObject vs. classic POCO, performance slowdown when RelaseGCPressureRowCount is below 1000)
- I think I need to enhance my test environment a lot in order to reproduce the different test scenarios. One thing which is also important is that the memory consumption in debugging is different than in a normal exceution. 
- I identified the CsvHelper library and the implementation of the GetRecords<dynamic> method as the "root" cause. I would want to write some tests to verify this assumption, perhaps there is a even a way to find the root cause of the GC pressure (the library is open source)

Unfortunately,  extending the test environment to reflect all the necessary scenarios will be a little bit more complex and therefore need some time. 

So for the time being, I would suggest to leave this issue open. You continue working with the current bug fix, and of course if you have new insights, please feel free to post them here  - any feedback is appreciated.  In the meanwhile, I will hopefully be able to write some tests and then decide how to further handle this problem.

**Comment by roadrunnerlenny** [comment] 2020-06-19 12:40
Still didn't have the time to fix this bug in it's entirety. But I guess the workaround with RelaseGCPressureRowCount is good enough, so I will close this here for the time being. 
It will stay on my Todo-list.

**Closed by roadrunnerlenny** 2020-06-19 12:40 UTC
Labels: bug
